name: Reddit-Discord Processor

on:
  schedule:
    # Run every 5 minutes (GitHub's minimum interval)
    - cron: '*/5 * * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  process-reddit-discord:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Run Reddit-Discord Processor
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RUN_ONCE: true
        run: node processor.js

      - name: Upload logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: processor-logs
          path: |
            processor.log
            error.log
          retention-days: 7 